services:
  log-monitor:
    container_name: log-monitor
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - TZ=Asia/Kolkata
    volumes:
      - ./logs:/logs
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1024M # Increased memory limit for ROS
